[google]
type = "service_account"
project_id = " hr-chatbot-drive-sync"
private_key_id = "14a12e72b44a36b0f302cfd23e64bc74e1615d92"
private_key = """-----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDOFkcLlkcwBk63
N5yhVJwQYmCPD3UPSFemURNS4UtzZ8mwR1y3ApMvKQLh3GkVQNrY7D9R5yxOj/pI
Yu7t/77J7zbbzKs6LJFngBCw4oTSD8wQbES/3Qj2hkggjJ/dRMq/X46sJKb3+mgA
cUFjfyNTenanqik/mu8M8uhefJv1ds+vO4mDVRHOYeN7Nyta4op8dUbJBLQwpkM3
GTkxD4UX+xQs6fXjhNaDKXRfWOJcU5Sqjjop5STpY5/yzJnGY7DUI9pUy73/o254
Hjr6bzz3QgNdOoEGEUnYmAxrnYjlOV762hNMxIipQK5LMDIgVfdaC7JeSAOWmFEp
l9aUmYGVAgMBAAECggEAB00+wyhV6Vuv2kn8ILMwvFvf8/GmQh5cDKZ+uscEt1gM
C1Tb8hgDQv5+/aWji386wcjNDYfVSAtN4NawhHo1Nk5lcTA1OOBvXm1pKfs8nXy1
zDcp0GpycNmdIJoa5+oSDOnD0lGSIOMcYDejC3VruP9zyMj8oSZKJflNRlu/4th8
hdv/2Vw/sjF5f11o4a6Zc+EmUx56hqijNJG3wRoium/xBU5bovnPXh+7ErtdC4XA
/Ul8ayN42QCn9nKgbk1mb2RxJF08IvuTUEjcWd6NSlZE/YFfUgm0J5Zoua80Xm+K
8IYa1oH3vEJ/4Iak4Lhp2FtgIg6PeXxEiSLT9mp6mQKBgQDuDrLwFrjTW1GrijkS
HMDmjUsn4IqetM1/au7ufPUHsMBFwFd1CU7F5E+FGR29qVHl/YuptIl4HN5D4dk7
/touVMXt1dU693ZIotDS4I1MM4VoNIa2jfiiTXetRg516hZx7bTKIcLhuCNBi10G
y1oz3QnRMXBJ35MN7Yabg6JmewKBgQDdnrZGXdN5DbmYpew2Af4DzHrNErloC7Rl
u04ylCSmy0M+vcjc38jhOGscpXBO7/8zTULDGr6uSkKpj3PSGc1Xohvvfnr6E+UD
AnxNj4eg2IMhP1+wg+PvED78krbCGOnirjc3deMyRcLIzhmTCW4j+3CEL9psUIRE
n5UwWFvDLwKBgAdWZKWJzcCV+/pxlDi+siNpD3v3K86gfAUFYr/vEg5eoE6GEywE
UW1AEENl9si1w1R3cCqW6fXNzfwBphR3UnpDGqauBJiAsCClBBK74R8MJ3yCwfQ2
hAdco+evVRrFUFPKo9vnFn6mkk+e4AspkWov0fGkuHVOctXnEFMSx5qpAoGAVAlB
zu73KJkGvpZ0OoqI2sHn8uldutFtZ4IeBdndCA5dgmYOy4pkLtro6uTk8FnbKIXs
gfUbRxXLr2ZBIfM8xTUoaKlKUpfGqFyB7Bs378sJ9kqEq3dnsBg1+ipb+L/fuGAd
ef9O1ppTYTedxP63cBeBM+69YYMqlKb6uGlY6msCgYEAk/i2c46RCXpFkJM01DgX
XNcHmfVUG74DTIuyURu9hwuQzbPxDYHSAAzHScvUhHuB00FQV583tix0Nzoq3EyW
WpHZUh/s8skUaBXXDLQFwyeTjVzg7ORpnWa1BXiYyr0q4w2ZlHOn0siIiKofuhSz
NYhVGau2cEJ379q5VL6PLPo-----END PRIVATE KEY-----"""
client_email = "hr-chatbot@hr-chatbot-drive-sync.iam.gserviceaccount.com"
client_id = "114588951462011404533"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hr-chatbot%40hr-chatbot-drive-sync.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
