[google]
type = "service_account"
project_id = "hr-chatbot-drive-sync "
private_key_id = " f05dff9d7c6f13d16064a670ab367843ded5c7f4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvGJG2zSeaKZqG
eqgiulBn/HgBGXOXQAjFlymnkQ2ufcu82xbTrP4OPYRKE10S6pUKe0cAX59BRxs9
1SzHgUJbVNrgAzWdhDcpw8crQpmPeFEbjxuXzUE6UVBCHFCWlJucgirGhfHeBbe2
gMESrEgs55PS+5+WbNBfI02Ri7IeDi4MhXif1QUiV9JtZhAE7k8/+u3joOWqRnK4
ndFhnUSLODmXb7BzSAIsgZjMEvKE1MJZRoaoRhI0URAiD1d9YvVb0jEM9sOiNRhe
vMkcNqb4ZG3wcZYLw8MxBGX/Qq4ITancPrSYJUR1QhgsDTL8sydrQDVCiOpIKCc4
rHVrEAnzAgMBAAECggEASaVO3JFrn8bx7LA4eerdmO8y1luLJ8nSJrGO3qD/HS5h
/Dw2XK/9Z6XuN23vjt5F89OoKHsPs9ghmB9Kp1sxutJ1ARW4flk3DoT/B64KgrK7
gpjtpSq6zbmXxUa9iqhUzz5cmYWLFrRW8hcznhQCg4ifv3UASbfY6LsjjB0yvLrN
/7cDy7ZOAHW5HMPUGTGS865BFW05AF27j8WBwdnkMHjMG9qo79mqQA0d9pTmSz1c
EFI3Bzr57NpxM4QF2Dt+m4fSwPP7ksxWwxSdUKssYBFx4RaBPS8//s3IdX7C7liP
QFlJQ0upt+7etF7+1m3Qfc/AMS4/23n6zOhNUcSv2QKBgQDTxck8BRjcui8aTkVT
Yyk4R6sHi7vcGU7xVYTmYl/ahETY+llF5wgYyo17ER0G+TdBXsFyCkIs8EKfqpxH
FClhsLuAd4aiMSbNcHkPNn8azPp7x7pJgJlZIoBJIBJlNxkrjXAuUf12CONfpH3a
7ikwSKn6tRH9fXIxhD8GnoNFtQKBgQDTqec7QESdzss2A3ZILiXlw6uyMJHw/K54
1pdw56wik+uZQlX1884Rp4Bl8y1M63PUYUxLtFUJLkiwELjrKs/rJMYmKTeo8WoI
/1cRTiV13nGW+RQmFqUKPaQdI3mTGEGjcEzqsyQJHy3a8gfONo95L7dy45bhtJ5B
pZON7cnaBwKBgQCAUeV4z+HbxZlLCEhrmbddWdfhb6M6X7987oPkEZHhV6pcC35S
pAY892c5PgpnslTv8FmpH1wv3LmSBBBD5YyZnDxRQJu85amMbG1+cVgdRj01CbXw
WdMRtp0jMiLTX8qJoF9sQdQiVIpp5sM4CH2+uxj8SAGJpxytsmN6QExszQKBgB88
y+tqqLXBdywZhrNQXDd0kTpTALbYE8exo9f92OGhgvuzVoxd1uO0HLbvFJhth0Ko
uWHS01nvgrq5PRE32EeTvcqT+qrsNgHt7SOYrN6gXZMyX07fuKuyPS4vthmHUuiU
AkYA+ih+eX3+ijhcxP/VkvVZsULOLSzzCru/hDKxAoGAG6VBUqxNOo3cwkOz7XZV
ti+8tg4f8POWtKh2xkNpt9f/YB5Y4sEA0cWQKslYfxo1axoPGVh1nb6EqCBYcqmc
ZbCAXiQuT7zSwrtPQO5MFlegTyZfoXA4H7dZU9Cin6N9ZoPKqRCJT5Jf3x+Z6OTY
qo3j0M4/LwWAOjbyRGNeWuw=
-----END PRIVATE KEY-----"""
client_email = "hr-chatbot@hr-chatbot-drive-sync.iam.gserviceaccount.com"
client_id = "114588951462011404533"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hr-chatbot%40hr-chatbot-drive-sync.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

ADMIN_PASSWORD = "hr_admin_123"